Store.Web/Areas/AdminPanel/Controllers/ProductsController.cs
using Application.Services.Products;
using DataLayer.Contexts;
using DataLayer.Entities.Discounts;
using DataLayer.Entities.Products;
using Domain.Products;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
namespace Store.Web.Areas.AdminPanel.Controllers;
public class ProductsController : AdminBaseController
{

    private readonly DBContext _dbContext;
    private readonly IProductService _productService;

    public ProductsController(DBContext dbContext, IProductService productService)
    {
        _dbContext = dbContext;
        _productService = productService;
    }

    #region Products

    [HttpGet("ProductsList")]
    public IActionResult ProductsList()
    {
        var products = _dbContext
            .Products
            .Include(a => a.Discounts.Where(a => a.IsDeleted == false && a.ExpireDate > DateTime.Now))
            .ToList();

        return View(products);
    }

    [HttpGet("CreateProduct")]
    public IActionResult CreateProduct()
    {
        ViewBag.cats = _productService.GetCategories();
        return View();
    }

    [HttpPost("CreateProduct")]
    public IActionResult CreateProduct(CreateProductDTO dto, IFormFile imageFile)
    {
        var res = _productService.CreateProduct(dto, imageFile);
        ViewBag.cats = _productService.GetCategories();
        if (res)
        {
            ViewBag.Mes = "محصول جدید ایجاد شد";
            return Redirect("/PanelAdmin/ProductsList");
        }
        else
        {
            ViewBag.Mes = "محصول جدید ایجاد نشد";
            return Redirect("/PanelAdmin/ProductsList");
        }
    }

    [HttpGet("EditProduct/{id}")]
    public IActionResult EditProduct(int id)
    {
        var product = _productService.GetProduct(id);
        ViewBag.cats = _productService.GetCategories();
        return View(product);
    }

    [HttpPost("EditProduct/{id}")]
    public IActionResult EditProduct(int id, EditProductDTO dto, IFormFile imageFile)
    {
        ViewBag.cats = _productService.GetCategories();
        var res = _productService.EditProduct(dto, imageFile);

        if (res)
        {
            ViewBag.Mes = "محصول ویرایش شد";
            return Redirect("/PanelAdmin/ProductsList");
        }
        else
        {
            ViewBag.Mes = "محصول ویرایش نشد";
            return Redirect("/PanelAdmin/ProductsList");
        }
    }

    [HttpGet("DeleteProduct/{id}")]
    public IActionResult DeleteProduct(int id)
    {
        var product = _productService.GetProduct(id);
        return View(product);
    }

    [HttpPost("DeleteProduct/{id}")]
    public IActionResult DeleteProduct(int id, EditProductDTO dto)
    {
        var res = _productService.DeleteProduct(dto.ProductId);

        if (res)
        {
            ViewBag.Mes = "محصول حذف شد";
            return Redirect("/PanelAdmin/ProductsList");
        }
        else
        {
            ViewBag.Mes = "محصول حذف نشد";
            return Redirect("/PanelAdmin/ProductsList");
        }
    }

    #endregion

    #region Discounts


    [HttpGet("Discount/{id}")]
    public IActionResult Discount(int id)
    {
        Discount dis = new Discount();

        dis.ProductId = id;

        return View(dis);
    }

    [HttpPost("Discount/{id}")]
    public IActionResult Discount(Discount dis, int id)
    {
        dis.ProductId = id;

        if (ModelState.IsValid)
        {
            var res = _productService.AddDiscount(dis);
            if (res)
            {
                ViewBag.Mes = "تخفیف اضافه شد";
                return Redirect("/PanelAdmin/ProductsList");
            }
            else
            {
                ViewBag.Mes = "تخفیف اضافه نشد";
                return Redirect("/PanelAdmin/ProductsList");
            }
        }

        return View(dis);
    }

    [HttpGet("DeleteDiscount/{id}")]
    public IActionResult DeleteDiscount(int id, string title)
    {
        ViewBag.Producttitle = title;
        ViewBag.id = id;
        return View();
    }

    [HttpPost("DeleteDiscount/{id}")]
    public IActionResult DeleteDiscount(int id)
    {
        var res = _productService.DeleteDiscount(id);

        if (res)
        {
            ViewBag.Mes = "تخفیف حذف شد";
            return Redirect("/PanelAdmin/ProductsList");
        }
        else
        {
            ViewBag.Mes = "تخفیف حذف نشد";
            return Redirect("/PanelAdmin/ProductsList");
        }
    }

    #endregion

    #region Colors

    [HttpGet("ColorsList/{productId}")]
    public IActionResult ColorsList(long productId)
    {
        var colors = _productService.GetColorProducts(productId);

        ViewBag.productId = productId;

        return View(colors);
    }

    [HttpGet("AddColor/{productId}")]
    public IActionResult AddColor(long productId)
    {
        return View();
    }

    [HttpPost("AddColor/{productId}")]
    public IActionResult AddColor(ColorProduct c, long productId)
    {
        c.ProductId = productId;
        var res = _productService.AddColor(c);

        switch (res)
        {
            case ColorResult.Null:
                TempData[WarningMessage] = "اطلاعات کامل نیست";
                break;
            case ColorResult.Error:
                TempData[ErrorMessage] = "خطایی رخ داد";
                break;
            case ColorResult.IsExist:
                TempData[WarningMessage] = "رنگ ثبت شده!";
                break;
            case ColorResult.Success:
                TempData[SuccessMessage] = "رنگ جدید با موفقیت ثبت شد";
                return Redirect($"/PanelAdmin/ColorsList/{c.ProductId}");
        }

        return View();
    }

    [HttpGet("UpdateColor/{colorId}/{productId}")]
    public IActionResult UpdateColor(long colorId, long productId)
    {
        var color = _productService.GetForUpdateColor(colorId);

        if(color == null)
        {
            TempData[SuccessMessage] = "رنگی یافت نشد!";
            return Redirect($"/PanelAdmin/ColorsList/{productId}");
        }

        return View(color);
    }

    [HttpPost("UpdateColor/{colorId}/{productId}")]
    public IActionResult UpdateColor(ColorProduct c,long colorId, long productId)
    {
        c.ProductId = productId;
        c.Id = colorId;
        var res = _productService.UpdateColor(c);

        switch (res)
        {
            case ColorResult.Null:
                TempData[WarningMessage] = "اطلاعات کامل نیست";
                break;
            case ColorResult.Error:
                TempData[ErrorMessage] = "خطایی رخ داد";
                break;
            case ColorResult.IsExist:
                TempData[WarningMessage] = "رنگ ثبت شده!";
                break;
            case ColorResult.Success:
                TempData[SuccessMessage] = "رنگ جدید با موفقیت ثبت شد";
                return Redirect($"/PanelAdmin/ColorsList/{c.ProductId}");
        }

        return View();
    }

    [HttpGet("DeleteColor/{colorId}/{productId}")]
    public IActionResult DeleteColor(long colorId, long productId)
    {
        ColorResult res = _productService.DeleteColor(colorId);

        if(res == ColorResult.Null)
        {
            TempData[WarningMessage] = "خطای رخ داده است";
            return Redirect($"/PanelAdmin/ColorsList/{productId}");
        }
        if (res == ColorResult.Error)
        {
            TempData[ErrorMessage] = "خطا";
            return Redirect($"/PanelAdmin/ColorsList/{productId}");
        }
        if (res == ColorResult.Success)
        {
            TempData[SuccessMessage] = "رنگ با موفقیت حذف شد";
            return Redirect($"/PanelAdmin/ColorsList/{productId}");
        }

        return Redirect($"/PanelAdmin/ColorsList/{productId}");
    }

    #endregion

}

Store.Web/Controllers/OrdersController.cs
using Application.Services.Orders;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Store.Web.Extentions;
namespace Store.Web.Controllers;
[Authorize]
public class OrdersController : BaseController
{

    private readonly IOrderService _orderService;
    public OrdersController(IOrderService orderService)
    {
        _orderService = orderService;
    }

    //[HttpPost("AddOrder/{productId}")]
    public IActionResult AddOrder(int productId)
    {
        int userId = User.GetUserId();

        var res = _orderService.AddOrder(productId, userId);

        if(res)
        {
            return Redirect($"/ProductDetail/{productId}?state=true");
        }
        else
        {
            return Redirect($"/ProductDetail/{productId}?state=true");
        }

    }


}

Store.Web/Controllers/ProductController.cs
using Application.Services.Products;
using Domain.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Store.Web.Extentions;
namespace Store.Web.Controllers;
public class ProductController : BaseController
{

    private readonly IProductService _productService;

    public ProductController(IProductService productService)
    {
        _productService = productService;
    }

    [HttpGet("ProductsList")]
    public IActionResult ProductsList(string title = null,string category = null)
    {

        List<ProductDto> products = _productService.GetAllProducts(title,category);

        ViewBag.title = title; ViewBag.category = category;

        return View(products);
    }

	[HttpGet("ProductDetail/{id}")]
	public IActionResult ProductDetail(int id,string state = null)
    {
        ViewBag.state = state;

       var product = _productService.GetProductDetail(id);

        if (product == null)
            return Redirect("/");

        _productService.UpdateVisit(product.Id);

        return View(product);
    }

    [Authorize]
    [HttpGet("AddProductToFav/{id}")]
    public IActionResult AddProductToFav(int id)
    {
        var product = _productService.AddProductToFav(id,User.GetUserId());

        if (product == false)
        {
            TempData[WarningMessage] = "خطایی رخ داده!";
            return Redirect($"/ProductDetail/{id}");
        }
        
        TempData[SuccessMessage] = "محصول به موارد مورده علاقه اضافه شد.";
        return Redirect($"/ProductDetail/{id}");
    }

}

Store.Web/Views/Product/ProductDetail.cshtml
@model Domain.Products.ProductDto
@{
    ViewData["Title"] = " جزییات محصول " + Model.Title;
}
<partial name="_PageNavbar" />

<div class="product_details variable_product mt-60 mb-60">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-6">
				<div class="product-details-tab">
					<div id="img-1" class="zoomWrapper single-zoom">
						<a href="#">
							<img id="zoom1" src="/images/@Model.ImageName" data-zoom-image="/images/@Model.ImageName" alt="big-1">
						</a>
					</div>
					@* <div class="single-zoom-thumb">
						<ul class="s-tab-zoom owl-carousel single-product-active" id="gallery_01">
							<li>
								<a href="#" class="elevatezoom-gallery active" data-update="" data-image="/site/img/product/productbig.jpg" data-zoom-image="/site/img/product/productbig.jpg">
									<img src="/site/img/product/productbig.jpg" alt="zo-th-1">
								</a>

							</li>
							<li>
								<a href="#" class="elevatezoom-gallery active" data-update="" data-image="/site/img/product/productbig1.jpg" data-zoom-image="/site/img/product/productbig1.jpg">
									<img src="/site/img/product/productbig1.jpg" alt="zo-th-1">
								</a>

							</li>
							<li>
								<a href="#" class="elevatezoom-gallery active" data-update="" data-image="/site/img/product/productbig2.jpg" data-zoom-image="/site/img/product/productbig2.jpg">
									<img src="/site/img/product/productbig2.jpg" alt="zo-th-1">
								</a>

							</li>
							<li>
								<a href="#" class="elevatezoom-gallery active" data-update="" data-image="/site/img/product/productbig3.jpg" data-zoom-image="/site/img/product/productbig3.jpg">
									<img src="/site/img/product/productbig3.jpg" alt="zo-th-1">
								</a>

							</li>
						</ul>
					</div> *@
				</div>
			</div>
			<div class="col-lg-6 col-md-6">
				<div class="product_d_right">
					<form asp-controller="Orders" asp-action="AddOrder">
						@if (ViewBag.state == "true")
						{
							<div class="alert alert-success">محصول به سبد خرید افزوده شد</div>
						}
						@if (ViewBag.state == "false")
						{
							<div class="alert alert-warning">محصول به سبد خرید افزوده نشد</div>
						}
						<h1>@Model.Title</h1>

						<div class=" product_ratting">
							<ul>
								<li><span><i class="fa fa-star"></i></span></li>
								<li><span><i class="fa fa-star"></i></span></li>
								<li><span><i class="fa fa-star"></i></span></li>
								<li><span><i class="fa fa-star"></i></span></li>
								<li><span><i class="fa fa-star"></i></span></li>
								<li class="review"><a href="#"> (امتیاز مشتریان) </a></li>
							</ul>

						</div>
						<div class="price_box">
							<span class="current_price">@Model.Price.ToString("#,0") تومان</span>
							@* <span class="old_price">80,000 تومان</span> *@

						</div>
						<div class="product_desc">
                            <p>
								@Html.Raw(Model.Description)
							</p>
						</div>
						<div class="product_variant color">
							<h3>گزینه های در دسترس</h3>
							<label>رنگ</label>
							<ul>
								<li class="color1">
									<a href="#"></a>
								</li>
								<li class="color2">
									<a href="#"></a>
								</li>
								<li class="color3">
									<a href="#"></a>
								</li>
								<li class="color4">
									<a href="#"></a>
								</li>
							</ul>
						</div>

						<div class="product_variant size">
							<label>اندازه</label>
							<select class="niceselect_option" id="color2" name="produc_color2">
								<option selected value="2">کوچک</option>
								<option value="3">متوسط</option>
								<option value="4">بزرگ</option>
								<option value="5">XL</option>
								<option value="6">XXL</option>
							</select>
						</div>
						<div class="product_variant quantity">
							<input type="hidden" name="productId" value="@Model.Id"/>
							<label>تعداد</label>
							<input min="1" max="100" value="1" type="number">
							<button class="button" type="submit">افزودن به سبد</button>

						</div>
						<div class=" product_d_action">
							<ul>
								<li><a asp-controller="Product" asp-action="AddProductToFav" asp-route-id="@Model.Id" title="افزودن به علاقه‌مندی‌ها">+ افزودن به علاقه‌مندی‌ها</a></li>
								<li><a href="#" title="مقایسه">+ مقایسه</a></li>
							</ul>
						</div>

					</form>

					<div class="product_d_meta">
						<span>شناسه: 1234567</span>
						<span>بازدید: @Model.TotalVisit</span>
                        <span>دسته: <a href="#">پوشاک</a></span>
						<span>
							برچسب ها:
							<a href="#">کودکانه</a> ،
							<a href="#">شلوار</a>
						</span>
					</div>
					<div class="priduct_social">
						<ul>
							<li><a class="facebook" href="#" title="فیسبوک"><i class="fa fa-facebook"></i> لایک</a></li>
							<li><a class="twitter" href="#" title="توییتر"><i class="fa fa-twitter"></i> توییت</a></li>
							<li><a class="pinterest" href="#" title="پینترست"><i class="fa fa-pinterest"></i> ذخیره</a></li>
							<li><a class="google-plus" href="#" title="گوگل پلاس"><i class="fa fa-google-plus"></i> اشتراک گذاری</a></li>
							<li><a class="telegram" href="#" title="تلگرام"><i class="fa fa-telegram"></i> تلگرام</a></li>
						</ul>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

Store.Web/Views/Product/ProductsList.cshtml
@model List<Domain.Products.ProductDto>
@{
    ViewData["Title"] = "محصولات";
}

<partial name="_PageNavbar" />
<input type="hidden" value="@ViewBag.category" name="category"/>
<input type="hidden" value="@ViewBag.title" name="title" />
<div class="shop_area shop_fullwidth mt-60 mb-60">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="shop_toolbar_wrapper">
					<div class="shop_toolbar_btn">

						<button data-role="grid_3" type="button" class=" btn-grid-3" data-toggle="tooltip" title="3"></button>

						<button data-role="grid_4" type="button" class="active btn-grid-4" data-toggle="tooltip" title="4"></button>

						<button data-role="grid_list" type="button" class="btn-list" data-toggle="tooltip" title="لیست"></button>
					</div>
					<div class="niceselect_container">
						<form action="#">
							<label>ترتیب:</label>
							<select class="select_option" name="orderby" id="short">
								<option selected value="1">امتیاز متوسط</option>
								<option value="2">محبوبیت</option>
								<option value="3">تعداد فروش</option>
								<option value="4">قیمت صعودی</option>
								<option value="5">قیمت نزولی</option>
								<option value="6">نام محصول</option>
							</select>
						</form>
					</div>
					<div class="page_amount">
						<p>نمایش 1-12 از 24 محصول</p>
					</div>
				</div>
				<!--shop toolbar end-->

                <div class="row shop_wrapper">
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <div class="col-xl-3 col-md-4 col-sm-6">
                                <article class="single_product">
                                    <figure>
                                        <div class="product_thumb">
                                            <a class="primary_img" asp-controller="Product" asp-action="ProductDetail" asp-route-id="@item.Id">
                                                <img src="/images/@item.ImageName" alt="">
                                            </a>
                                            <a class="secondary_img" asp-controller="Product" asp-action="ProductDetail" asp-route-id="@item.Id">
                                                <img src="/site/img/product/product2.jpg" alt="">
                                            </a>
                                            <div class="label_product">
                                                <span class="label_sale">فروش</span>
                                            </div>
                                            <div class="action_links">
                                                <ul>
                                                    <li class="wishlist">
                                                        <a href="wishlist.html" title="افزودن به علاقه‌مندی‌ها">
                                                            <i class="fa fa-heart-o" aria-hidden="true"></i>
                                                        </a>
                                                    </li>
                                                    <li class="compare">
                                                        <a href="#" title="مقایسه"><span class="ion-levels"></span></a>
                                                    </li>
                                                    <li class="quick_button">
                                                        <a href="#" data-toggle="modal" data-target="#modal_box" title="مشاهده سریع">
                                                             <span class="ion-ios-search-strong"></span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="add_to_cart">
                                                <a href="cart.html" title="افزودن به سبد">افزودن به سبد</a>
                                            </div>
                                        </div>
                                        <div class="product_content grid_content">
                                            <div class="price_box">
                                                @* <span class="old_price">86,000 تومان</span> *@
                                                <span class="current_price">@item.Price.ToString("#,0") تومان</span>
                                            </div>
                                            <div class="product_ratings">
                                                <ul>
                                                    <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                    <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                    <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                    <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                    <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                </ul>
                                            </div>
                                            <h3 class="product_name grid_name">
                                                <a asp-controller="Product" asp-action="ProductDetail" asp-route-id="@item.Id">@item.Title</a>
                                            </h3>
                                        </div>
                                        <div class="product_content list_content">
                                            <div class="left_caption">
                                                <div class="price_box">
                                                    @* <span class="old_price">86,000 تومان</span> *@
                                                    <span class="current_price">@item.Price تومان</span>
                                                </div>
                                                <h3 class="product_name">
                                                    <a href="product-details.html">@item.Title</a>
                                                </h3>
                                                <div class="product_ratings">
                                                    <ul>
                                                        <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                        <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                        <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                        <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                        <li><a href="#"><i class="ion-android-star-outline"></i></a></li>
                                                    </ul>
                                                </div>
                                                <div class="product_desc">
                                                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.</p>
                                                </div>
                                            </div>
                                            <div class="right_caption">
                                                <div class="add_to_cart">
                                                    <a href="cart.html" title="افزودن به سبد">افزودن به سبد</a>
                                                </div>
                                                <div class="action_links">
                                                    <ul>
                                                        <li class="wishlist">
                                                            <a href="wishlist.html" title="افزودن به علاقه‌مندی‌ها"><i class="fa fa-heart-o" aria-hidden="true"></i> افزودن به علاقه‌مندی‌ها</a>
                                                        </li>
                                                        <li class="compare">
                                                            <a href="#" title="مقایسه"><span class="ion-levels"></span> مقایسه</a>
                                                        </li>
                                                        <li class="quick_button">
                                                            <a href="#" data-toggle="modal" data-target="#modal_box" title="مشاهده سریع"> <span class="ion-ios-search-strong"></span> نمایش سریع</a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </article>
                            </div>
                        }
                    }
                    
                </div>

				<div class="shop_toolbar t_bottom">
					<div class="pagination">
						<ul>
							<li class="current"><span>1</span></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li class="next"><a href="#">بعدی</a></li>
							<li><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
						</ul>
					</div>
				</div>
				<!--shop toolbar end-->
				<!--shop wrapper end-->
			</div>
		</div>
	</div>
</div>